# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 900)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(15, 32, 39, 255), stop:1 rgba(44, 83, 100, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame = QtWidgets.QFrame(self.centralwidget)
        self.top_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.top_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.verticalLayout.addWidget(self.top_frame)
        self.central_frame = QtWidgets.QFrame(self.centralwidget)
        self.central_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.central_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.central_frame.setObjectName("central_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.central_frame)
        self.horizontalLayout.setContentsMargins(100, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_frame = QtWidgets.QFrame(self.central_frame)
        self.left_frame.setMinimumSize(QtCore.QSize(750, 0))
        self.left_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.left_frame)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 611))
        self.frame_6.setStyleSheet("QFrame#frame_6{\n"
"image: url(:/images/images/logo.png);\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.map_frame = QtWidgets.QFrame(self.frame_6)
        self.map_frame.setGeometry(QtCore.QRect(0, 0, 751, 611))
        self.map_frame.setStyleSheet("QFrame#map_frame{\n"
"    image: url(:/images/images/map.png);\n"
"}")
        self.map_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.map_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.map_frame.setObjectName("map_frame")
        self.verticalLayout_2.addWidget(self.frame_6)
        self.robot_status = QtWidgets.QFrame(self.left_frame)
        self.robot_status.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.robot_status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.robot_status.setObjectName("robot_status")
        self.verticalLayout_2.addWidget(self.robot_status)
        self.horizontalLayout.addWidget(self.left_frame)
        self.centered = QtWidgets.QFrame(self.central_frame)
        self.centered.setMaximumSize(QtCore.QSize(280, 16777215))
        self.centered.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.centered.setFrameShadow(QtWidgets.QFrame.Raised)
        self.centered.setObjectName("centered")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centered)
        self.verticalLayout_3.setContentsMargins(-1, 25, -1, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.loading_frame = QtWidgets.QFrame(self.centered)
        self.loading_frame.setMinimumSize(QtCore.QSize(0, 336))
        self.loading_frame.setStyleSheet("QFrame#loading_frame{\n"
"border: 3px solid #c4c4c4;\n"
"border-radius: 30px;\n"
"}")
        self.loading_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.loading_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loading_frame.setObjectName("loading_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.loading_frame)
        self.gridLayout.setContentsMargins(15, 25, 15, 25)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(16)
        self.gridLayout.setObjectName("gridLayout")
        self.load_r = QtWidgets.QPushButton(self.loading_frame)
        self.load_r.setMinimumSize(QtCore.QSize(0, 40))
        self.load_r.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: transparent;\n"
"\n"
"background-color: #4286f4;\n"
"}")
        self.load_r.setObjectName("load_r")
        self.gridLayout.addWidget(self.load_r, 2, 1, 1, 1)
        self.clear_btn = QtWidgets.QPushButton(self.loading_frame)
        self.clear_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.clear_btn.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(208, 208, 208);\n"
"    color: rgb(66, 66, 66);\n"
"border:0px;\n"
"}")
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout.addWidget(self.clear_btn, 9, 1, 1, 1)
        self.unload_l = QtWidgets.QPushButton(self.loading_frame)
        self.unload_l.setMinimumSize(QtCore.QSize(105, 40))
        self.unload_l.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: transparent;\n"
"\n"
"background-color: #4286f4;\n"
"}")
        self.unload_l.setObjectName("unload_l")
        self.gridLayout.addWidget(self.unload_l, 5, 1, 1, 1)
        self.load_d = QtWidgets.QPushButton(self.loading_frame)
        self.load_d.setMinimumSize(QtCore.QSize(0, 40))
        self.load_d.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: transparent;\n"
"\n"
"background-color: #4286f4;\n"
"}")
        self.load_d.setObjectName("load_d")
        self.gridLayout.addWidget(self.load_d, 2, 0, 1, 1)
        self.unload_r = QtWidgets.QPushButton(self.loading_frame)
        self.unload_r.setMinimumSize(QtCore.QSize(105, 40))
        self.unload_r.setMaximumSize(QtCore.QSize(80, 16777215))
        self.unload_r.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: transparent;\n"
"\n"
"background-color: #4286f4;\n"
"}")
        self.unload_r.setObjectName("unload_r")
        self.gridLayout.addWidget(self.unload_r, 6, 1, 1, 1)
        self.tur2_btn = QtWidgets.QPushButton(self.loading_frame)
        self.tur2_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.tur2_btn.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(208, 208, 208);\n"
"    color: rgb(66, 66, 66);\n"
"border:0px;\n"
"}")
        self.tur2_btn.setObjectName("tur2_btn")
        self.gridLayout.addWidget(self.tur2_btn, 8, 1, 1, 1)
        self.load_u = QtWidgets.QPushButton(self.loading_frame)
        self.load_u.setMinimumSize(QtCore.QSize(0, 40))
        self.load_u.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: transparent;\n"
"\n"
"background-color: #4286f4;\n"
"}")
        self.load_u.setObjectName("load_u")
        self.gridLayout.addWidget(self.load_u, 1, 0, 1, 1)
        self.loading_lineedit = QtWidgets.QLineEdit(self.loading_frame)
        self.loading_lineedit.setMinimumSize(QtCore.QSize(223, 40))
        self.loading_lineedit.setStyleSheet("background-color: #203A43;\n"
"border: 2px solid #203A43;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);")
        self.loading_lineedit.setObjectName("loading_lineedit")
        self.gridLayout.addWidget(self.loading_lineedit, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.loading_frame)
        self.label_8.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
"color: rgb(240, 235, 227);")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.load_l = QtWidgets.QPushButton(self.loading_frame)
        self.load_l.setMinimumSize(QtCore.QSize(105, 40))
        self.load_l.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: transparent;\n"
"\n"
"background-color: #4286f4;\n"
"}")
        self.load_l.setObjectName("load_l")
        self.gridLayout.addWidget(self.load_l, 1, 1, 1, 1)
        self.unload_d = QtWidgets.QPushButton(self.loading_frame)
        self.unload_d.setMinimumSize(QtCore.QSize(111, 40))
        self.unload_d.setMaximumSize(QtCore.QSize(80, 16777215))
        self.unload_d.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: transparent;\n"
"\n"
"background-color: #4286f4;\n"
"}")
        self.unload_d.setObjectName("unload_d")
        self.gridLayout.addWidget(self.unload_d, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.loading_frame)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_7.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
"color: rgb(240, 235, 227);")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.start_btn = QtWidgets.QPushButton(self.loading_frame)
        self.start_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.start_btn.setStyleSheet("QPushButton{\n"
"    background-color:#4286f4;\n"
"border: 0px;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(208, 208, 208);\n"
"    color: rgb(66, 66, 66);\n"
"}")
        self.start_btn.setObjectName("start_btn")
        self.gridLayout.addWidget(self.start_btn, 9, 0, 1, 1)
        self.unloading_lineedit = QtWidgets.QLineEdit(self.loading_frame)
        self.unloading_lineedit.setMinimumSize(QtCore.QSize(223, 40))
        self.unloading_lineedit.setStyleSheet("background-color: #203A43;\n"
"border: 2px solid #203A43;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);")
        self.unloading_lineedit.setObjectName("unloading_lineedit")
        self.gridLayout.addWidget(self.unloading_lineedit, 7, 0, 1, 1)
        self.unload_u = QtWidgets.QPushButton(self.loading_frame)
        self.unload_u.setMinimumSize(QtCore.QSize(0, 40))
        self.unload_u.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: transparent;\n"
"\n"
"background-color: #4286f4;\n"
"}")
        self.unload_u.setObjectName("unload_u")
        self.gridLayout.addWidget(self.unload_u, 5, 0, 1, 1)
        self.tur1_btn = QtWidgets.QPushButton(self.loading_frame)
        self.tur1_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.tur1_btn.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(208, 208, 208);\n"
"    color: rgb(66, 66, 66);\n"
"border:0px;\n"
"}")
        self.tur1_btn.setObjectName("tur1_btn")
        self.gridLayout.addWidget(self.tur1_btn, 8, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.loading_frame)
        self.start_frame = QtWidgets.QFrame(self.centered)
        self.start_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.start_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.start_frame.setObjectName("start_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.start_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3.addWidget(self.start_frame)
        self.horizontalLayout.addWidget(self.centered)
        self.right_frame = QtWidgets.QFrame(self.central_frame)
        self.right_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.right_frame)
        self.verticalLayout_5.setContentsMargins(0, 25, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.speed_and_battery = QtWidgets.QFrame(self.right_frame)
        self.speed_and_battery.setMinimumSize(QtCore.QSize(0, 550))
        self.speed_and_battery.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.speed_and_battery.setFrameShadow(QtWidgets.QFrame.Raised)
        self.speed_and_battery.setObjectName("speed_and_battery")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.speed_and_battery)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(25)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.velocity_container = QtWidgets.QFrame(self.speed_and_battery)
        self.velocity_container.setMinimumSize(QtCore.QSize(250, 250))
        self.velocity_container.setMaximumSize(QtCore.QSize(250, 250))
        self.velocity_container.setStyleSheet("QFrame#velocity_container{\n"
"background-color: #203A43;\n"
"border-radius: 125;\n"
"}")
        self.velocity_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.velocity_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.velocity_container.setObjectName("velocity_container")
        self.progress_frame = QtWidgets.QFrame(self.velocity_container)
        self.progress_frame.setGeometry(QtCore.QRect(0, 0, 250, 250))
        self.progress_frame.setStyleSheet("QFrame#progress_frame{\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.49 rgba(255, 255, 255, 0), stop:0.5 rgba(66, 134, 244, 255));\n"
"border-radius: 125px;\n"
"}\n"
"")
        self.progress_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress_frame.setObjectName("progress_frame")
        self.frame = QtWidgets.QFrame(self.progress_frame)
        self.frame.setGeometry(QtCore.QRect(20, 20, 210, 210))
        self.frame.setStyleSheet("background-color: #22414e;\n"
"border-radius: 105px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.speed_label = QtWidgets.QLabel(self.frame)
        self.speed_label.setGeometry(QtCore.QRect(40, 80, 131, 51))
        self.speed_label.setStyleSheet("font: 63 32pt \"Bahnschrift SemiBold\";\n"
"color: #4286f4;")
        self.speed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_label.setObjectName("speed_label")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(70, 130, 80, 40))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_10.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
"color: rgb(240, 235, 227);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.velocity_container)
        self.battery_frame = QtWidgets.QFrame(self.speed_and_battery)
        self.battery_frame.setMinimumSize(QtCore.QSize(0, 288))
        self.battery_frame.setMaximumSize(QtCore.QSize(270, 16777215))
        self.battery_frame.setStyleSheet("QFrame#battery_frame{\n"
"\n"
"border: 3px solid #c4c4c4;\n"
"border-radius: 30px;\n"
"}")
        self.battery_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.battery_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.battery_frame.setObjectName("battery_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.battery_frame)
        self.verticalLayout_7.setContentsMargins(15, 12, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.battery = QtWidgets.QFrame(self.battery_frame)
        self.battery.setMaximumSize(QtCore.QSize(200, 16777215))
        self.battery.setStyleSheet("QFrame#battery{\n"
"image: url(:/images/images/battery.png);\n"
"}")
        self.battery.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.battery.setFrameShadow(QtWidgets.QFrame.Raised)
        self.battery.setObjectName("battery")
        self.frame_3 = QtWidgets.QFrame(self.battery)
        self.frame_3.setGeometry(QtCore.QRect(18, 31, 155, 76))
        self.frame_3.setStyleSheet("background-color: #4286f4;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.battery_pct = QtWidgets.QFrame(self.battery)
        self.battery_pct.setGeometry(QtCore.QRect(18, 31, 155, 76))
        self.battery_pct.setStyleSheet("background-color: #234351;")
        self.battery_pct.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.battery_pct.setFrameShadow(QtWidgets.QFrame.Raised)
        self.battery_pct.setObjectName("battery_pct")
        self.verticalLayout_7.addWidget(self.battery)
        self.frame_2 = QtWidgets.QFrame(self.battery_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(0, 0, 10, 20)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_11.setStyleSheet("font: 63 32pt \"Bahnschrift SemiBold\";\n"
"color: #4286f4;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_12.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
"color: rgb(240, 235, 227);")
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setStyleSheet("font: 63 18pt \"Bahnschrift SemiBold\";\n"
"color: #4286f4;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_13.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
"color: rgb(240, 235, 227);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setStyleSheet("font: 63 18pt \"Bahnschrift SemiBold\";\n"
"color: #4286f4;")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.verticalLayout_6.addWidget(self.battery_frame)
        self.verticalLayout_5.addWidget(self.speed_and_battery)
        self.tbk = QtWidgets.QFrame(self.right_frame)
        self.tbk.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tbk.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tbk.setObjectName("tbk")
        self.verticalLayout_5.addWidget(self.tbk)
        self.horizontalLayout.addWidget(self.right_frame)
        self.verticalLayout.addWidget(self.central_frame)
        self.bottom_frame = QtWidgets.QFrame(self.centralwidget)
        self.bottom_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottom_frame)
        self.horizontalLayout_2.setContentsMargins(100, -1, -1, 28)
        self.horizontalLayout_2.setSpacing(60)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.step_1 = QtWidgets.QFrame(self.bottom_frame)
        self.step_1.setMaximumSize(QtCore.QSize(250, 170))
        self.step_1.setStyleSheet("QFrame#step_1{\n"
"border: 3px solid #c4c4c4;\n"
"border-radius: 30px;\n"
"}")
        self.step_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.step_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.step_1.setObjectName("step_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.step_1)
        self.gridLayout_4.setContentsMargins(15, 15, 30, 15)
        self.gridLayout_4.setHorizontalSpacing(50)
        self.gridLayout_4.setVerticalSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.step1_label = QtWidgets.QLabel(self.step_1)
        self.step1_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.step1_label.setStyleSheet("font: 63 24pt \"Bahnschrift SemiBold\";\n"
"color: #4286f4;")
        self.step1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.step1_label.setObjectName("step1_label")
        self.gridLayout_4.addWidget(self.step1_label, 0, 0, 1, 1)
        self.loading1 = QtWidgets.QLabel(self.step_1)
        self.loading1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.loading1.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
"color: #4286f4;")
        self.loading1.setAlignment(QtCore.Qt.AlignCenter)
        self.loading1.setObjectName("loading1")
        self.gridLayout_4.addWidget(self.loading1, 1, 0, 1, 1)
        self.unloading1 = QtWidgets.QLabel(self.step_1)
        self.unloading1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.unloading1.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
"color: #4286f4;")
        self.unloading1.setAlignment(QtCore.Qt.AlignCenter)
        self.unloading1.setObjectName("unloading1")
        self.gridLayout_4.addWidget(self.unloading1, 2, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.step_1)
        self.step_2 = QtWidgets.QFrame(self.bottom_frame)
        self.step_2.setMaximumSize(QtCore.QSize(250, 170))
        self.step_2.setStyleSheet("QFrame#step_2{\n"
"border: 3px solid #c4c4c4;\n"
"border-radius: 30px;\n"
"}")
        self.step_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.step_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.step_2.setObjectName("step_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.step_2)
        self.gridLayout_5.setContentsMargins(15, 15, 30, 15)
        self.gridLayout_5.setHorizontalSpacing(50)
        self.gridLayout_5.setVerticalSpacing(2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.step2_label = QtWidgets.QLabel(self.step_2)
        self.step2_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.step2_label.setStyleSheet("font: 63 24pt \"Bahnschrift SemiBold\";\n"
"color: rgb(141, 141, 141);")
        self.step2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.step2_label.setObjectName("step2_label")
        self.gridLayout_5.addWidget(self.step2_label, 0, 0, 1, 1)
        self.loading2 = QtWidgets.QLabel(self.step_2)
        self.loading2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.loading2.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
"color: rgb(141, 141, 141);")
        self.loading2.setAlignment(QtCore.Qt.AlignCenter)
        self.loading2.setObjectName("loading2")
        self.gridLayout_5.addWidget(self.loading2, 1, 0, 1, 1)
        self.unloading2 = QtWidgets.QLabel(self.step_2)
        self.unloading2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.unloading2.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
"color: rgb(141, 141, 141);")
        self.unloading2.setAlignment(QtCore.Qt.AlignCenter)
        self.unloading2.setObjectName("unloading2")
        self.gridLayout_5.addWidget(self.unloading2, 2, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.step_2)
        self.frame_5 = QtWidgets.QFrame(self.bottom_frame)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 170))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(39, 59, 41, 41))
        self.label_3.setStyleSheet("color: #EB1D36;\n"
"font: 83 28pt \"Bahnschrift Bold\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(167, 59, 31, 31))
        self.label_4.setStyleSheet("color: #EB1D36;\n"
"font: 83 18pt \"Bahnschrift Bold\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(135, 59, 41, 41))
        self.label_5.setStyleSheet("color: #EB1D36;\n"
"font: 83 28pt \"Bahnschrift Bold\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(85, 94, 41, 51))
        self.label_6.setStyleSheet("color: #EB1D36;\n"
"font: 83 28pt \"Bahnschrift Bold\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(85, 10, 41, 51))
        self.label_9.setStyleSheet("color: #EB1D36;\n"
"font: 83 28pt \"Bahnschrift Bold\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(90, 140, 31, 31))
        self.label_16.setStyleSheet("color: #EB1D36;\n"
"font: 83 18pt \"Bahnschrift Bold\";")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        self.label_17.setGeometry(QtCore.QRect(90, 0, 31, 31))
        self.label_17.setStyleSheet("color: #EB1D36;\n"
"font: 83 18pt \"Bahnschrift Bold\";")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(10, 59, 31, 31))
        self.label_18.setStyleSheet("color: #EB1D36;\n"
"font: 83 18pt \"Bahnschrift Bold\";")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.final_lineedit = QtWidgets.QLineEdit(self.frame_5)
        self.final_lineedit.setGeometry(QtCore.QRect(210, 90, 223, 40))
        self.final_lineedit.setMinimumSize(QtCore.QSize(223, 40))
        self.final_lineedit.setStyleSheet("background-color: #203A43;\n"
"border: 2px solid #203A43;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);")
        self.final_lineedit.setObjectName("final_lineedit")
        self.final_l = QtWidgets.QPushButton(self.frame_5)
        self.final_l.setGeometry(QtCore.QRect(580, 40, 105, 40))
        self.final_l.setMinimumSize(QtCore.QSize(105, 40))
        self.final_l.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: transparent;\n"
"\n"
"background-color: #4286f4;\n"
"}")
        self.final_l.setObjectName("final_l")
        self.final_u = QtWidgets.QPushButton(self.frame_5)
        self.final_u.setGeometry(QtCore.QRect(210, 40, 111, 40))
        self.final_u.setMinimumSize(QtCore.QSize(0, 40))
        self.final_u.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: transparent;\n"
"\n"
"background-color: #4286f4;\n"
"}")
        self.final_u.setObjectName("final_u")
        self.final_d = QtWidgets.QPushButton(self.frame_5)
        self.final_d.setGeometry(QtCore.QRect(330, 40, 111, 40))
        self.final_d.setMinimumSize(QtCore.QSize(111, 40))
        self.final_d.setMaximumSize(QtCore.QSize(80, 16777215))
        self.final_d.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: transparent;\n"
"\n"
"background-color: #4286f4;\n"
"}")
        self.final_d.setObjectName("final_d")
        self.final_r = QtWidgets.QPushButton(self.frame_5)
        self.final_r.setGeometry(QtCore.QRect(450, 40, 105, 40))
        self.final_r.setMinimumSize(QtCore.QSize(105, 40))
        self.final_r.setMaximumSize(QtCore.QSize(80, 16777215))
        self.final_r.setStyleSheet("QPushButton{\n"
"border: 2px solid #4286f4;\n"
"border-radius: 15px;\n"
"    font: 63 14pt \"Bahnschrift SemiBold\";\n"
"    color: rgb(209, 209, 209);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: transparent;\n"
"\n"
"background-color: #4286f4;\n"
"}")
        self.final_r.setObjectName("final_r")
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        self.label_19.setGeometry(QtCore.QRect(210, 10, 111, 23))
        self.label_19.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
"color: rgb(240, 235, 227);")
        self.label_19.setObjectName("label_19")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(210, 140, 121, 21))
        self.label.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
"color: rgb(240, 235, 227);")
        self.label.setObjectName("label")
        self.time_label = QtWidgets.QLabel(self.frame_5)
        self.time_label.setGeometry(QtCore.QRect(340, 140, 111, 21))
        self.time_label.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
"color: #4286f4;")
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.bottom_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load_r.setText(_translate("MainWindow", "R"))
        self.clear_btn.setText(_translate("MainWindow", "Sil"))
        self.unload_l.setText(_translate("MainWindow", "L"))
        self.load_d.setText(_translate("MainWindow", "D"))
        self.unload_r.setText(_translate("MainWindow", "R"))
        self.tur2_btn.setText(_translate("MainWindow", "2.Yükleme"))
        self.load_u.setText(_translate("MainWindow", "U"))
        self.label_8.setText(_translate("MainWindow", "Boşaltma"))
        self.load_l.setText(_translate("MainWindow", "L"))
        self.unload_d.setText(_translate("MainWindow", "D"))
        self.label_7.setText(_translate("MainWindow", "Yükleme"))
        self.start_btn.setText(_translate("MainWindow", "Başlat"))
        self.unload_u.setText(_translate("MainWindow", "U"))
        self.tur1_btn.setText(_translate("MainWindow", "1.Yükleme"))
        self.speed_label.setText(_translate("MainWindow", "0.2"))
        self.label_10.setText(_translate("MainWindow", "m/s"))
        self.label_11.setText(_translate("MainWindow", "%40"))
        self.label_12.setText(_translate("MainWindow", "Volt"))
        self.label_14.setText(_translate("MainWindow", "25 V"))
        self.label_13.setText(_translate("MainWindow", "Akım"))
        self.label_15.setText(_translate("MainWindow", "11 A"))
        self.step1_label.setText(_translate("MainWindow", "1. Tur"))
        self.loading1.setText(_translate("MainWindow", "Yükleme"))
        self.unloading1.setText(_translate("MainWindow", "Boşaltma"))
        self.step2_label.setText(_translate("MainWindow", "2. Tur"))
        self.loading2.setText(_translate("MainWindow", "Yükleme"))
        self.unloading2.setText(_translate("MainWindow", "Boşaltma"))
        self.label_3.setText(_translate("MainWindow", "←"))
        self.label_4.setText(_translate("MainWindow", "R"))
        self.label_5.setText(_translate("MainWindow", "→"))
        self.label_6.setText(_translate("MainWindow", "↓"))
        self.label_9.setText(_translate("MainWindow", "↑"))
        self.label_16.setText(_translate("MainWindow", "D"))
        self.label_17.setText(_translate("MainWindow", "U"))
        self.label_18.setText(_translate("MainWindow", "L"))
        self.final_l.setText(_translate("MainWindow", "L"))
        self.final_u.setText(_translate("MainWindow", "U"))
        self.final_d.setText(_translate("MainWindow", "D"))
        self.final_r.setText(_translate("MainWindow", "R"))
        self.label_19.setText(_translate("MainWindow", "Bitiş"))
        self.label.setText(_translate("MainWindow", "Görev süresi:"))
        self.time_label.setText(_translate("MainWindow", "0 dk"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
